backend:
  name: github
  repo: Shakalinux/fiel-informatica-catalogo
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "data/produtos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Preço", name: "preco", widget: "string" }
      - { label: "Descrição", name: "descricao", widget: "text" }
      - { label: "Imagem", name: "imagem", widget: "image" }
      - { label: "Categoria", name: "categoria", widget: "select", options: ["Notebooks", "Acessórios", "Componentes", "Periféricos"] }

  - name: "servicos"
    label: "Serviços"
    folder: "data/servicos"
    create: true
    fields:
      - { label: "Nome do Serviço", name: "nome", widget: "string" }
      - { label: "Preço", name: "preco", widget: "string" }
      - { label: "Descrição", name: "descricao", widget: "markdown" }
      - { label: "Imagem", name: "imagem", widget: "image" }
